export default [
  { name: 'card0', status: false, img: 'image1.png', match: false, group: 1 },
  { name: 'card1', status: false, img: 'image1.png', match: false, group: 1 },
  { name: 'card2', status: false, img: 'image2.png', match: false, group: 2 },
  { name: 'card3', status: false, img: 'image2.png', match: false, group: 2 },
  { name: 'card4', status: false, img: 'image3.png', match: false, group: 3 },
  { name: 'card5', status: false, img: 'image3.png', match: false, group: 3 },
  { name: 'card6', status: false, img: 'image4.png', match: false, group: 4 },
  { name: 'card7', status: false, img: 'image4.png', match: false, group: 4 },
  { name: 'card8', status: false, img: 'image5.png', match: false, group: 5 },
  { name: 'card9', status: false, img: 'image5.png', match: false, group: 5 },
  { name: 'card10', status: false, img: 'image6.png', match: false, group: 6 },
  { name: 'card11', status: false, img: 'image6.png', match: false, group: 6 },
  { name: 'card12', status: false, img: 'image7.png', match: false, group: 7 },
  { name: 'card13', status: false, img: 'image7.png', match: false, group: 7 },
  { name: 'card14', status: false, img: 'image8.png', match: false, group: 8 },
  { name: 'card15', status: false, img: 'image8.png', match: false, group: 8 },
  { name: 'card16', status: false, img: 'image9.png', match: false, group: 9 },
  { name: 'card17', status: false, img: 'image9.png', match: false, group: 9 },
  {
    name: 'card18',
    status: false,
    img: 'image10.png',
    match: false,
    group: 10,
  },
  {
    name: 'card19',
    status: false,
    img: 'image10.png',
    match: false,
    group: 10,
  },
];
